version: '3.8'

services:
  be:
    build:
      context: .
      target: backend
      dockerfile: ./Dockerfile
    networks:
      - nesjs-network
    volumes:
      - ./data:/usr/src/app/data
  fe:
    build:
      context: .
      target: frontend
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
    networks:
      - nesjs-network
    volumes:
      - ./data/images:/usr/share/nginx/html/images

networks:
  nesjs-network:
